version: '3'

services:
  web:
    image: docker-django-v0.0:latest 
    command: python /home/app/webapp/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app/webapp
    depends_on:
      - db
  db:
    image: postgres:latest  
    environment:
      POSTGRES_DB: inspect_code
      POSTGRES_USER: code_admin
      POSTGRES_PASSWORD: satoshibuterin1933
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  celery:
    image: docker-django-celery:latest 
    command: celery -A code_check worker --loglevel=info  
    volumes:
      - .:/home/app/webapp
    depends_on:
      - redis
  celery-beat:
    build:
      context: . 
      dockerfile: Dockerfile.beat
    command: celery -A code_check beat --loglevel=info
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=code_check.settings
volumes:
  postgres_data:
