
FROM python:3.8

RUN pip install celery[redis]  

RUN mkdir /app
WORKDIR /app

COPY . /app

ENV DJANGO_SETTINGS_MODULE=your_project_name.settings

CMD ["celery", "-A", "code_check", "beat", "--loglevel=info"]
